name: Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest', 'macos-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

